# Generated by Django 6.0.1 on 2026-01-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_taskhistory_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "permissions": [
                    ("can_assign_task", "Can assign task"),
                    ("can_update_task", "Can update task"),
                    ("can_view_all_tasks", "Can view all tasks"),
                    ("can_delete_task", "Can delete tasks"),
                ]
            },
        ),
        migrations.AlterField(
            model_name="task",
            name="assigned_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
