# Generated by Django 6.0.1 on 2026-02-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Enter 10 digit mobile number",
                max_length=10,
                null=True,
                unique=True,
            ),
        ),
    ]
