# Generated by Django 6.0.1 on 2026-02-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="properties",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
