# Generated by Django 6.0.1 on 2026-02-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_properties_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="properties",
            name="location",
            field=models.CharField(
                choices=[
                    ("hyderabad", "Hyderabad"),
                    ("bangalore", "Bangalore"),
                    ("chennai", "Chennai"),
                ],
                default=None,
                max_length=50,
            ),
        ),
    ]
