# Generated by Django 6.0.1 on 2026-02-09 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_properties_location"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("can_view_dashboard", "Can view dashboard"),
                    ("can_view_admin", "Can view admin section"),
                    ("can_view_products", "Can view products"),
                    ("can_view_leads", "Can view leads"),
                    ("can_view_permissions", "Can view permissions"),
                    ("can_view_contacts", "Can view contacts"),
                ]
            },
        ),
    ]
