# Generated by Django 6.0.1 on 2026-02-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_alter_user_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="profile_images/"
            ),
        ),
    ]
