# Generated by Django 6.0.1 on 2026-02-11 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_alter_user_profile_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "permissions": [
                    ("can_assign_task", "Can assign task"),
                    ("can_update_task", "Can update task"),
                    ("can_view_all_tasks", "Can view all tasks"),
                    ("can_delete_task", "Can delete tasks"),
                    ("view_lead", "Can view leads"),
                    ("add_lead", "Can add leads"),
                    ("change_lead", "Can update leads"),
                    ("delete_lead", "Can delete leads"),
                ]
            },
        ),
    ]
