# Generated by Django 6.0.1 on 2026-02-11 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="properties",
            options={
                "permissions": [
                    ("view_product", "View Products"),
                    ("add_product", "Add Products"),
                    ("change_product", "Update Products"),
                    ("delete_product", "Delete Products"),
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="task",
            options={
                "permissions": [
                    ("can_assign_lead", "Can assign task"),
                    ("can_update_lead", "Can update task"),
                    ("can_view_lead", "Can view all tasks"),
                    ("can_delete_lead", "Can delete tasks"),
                ]
            },
        ),
    ]
