# Generated by Django 6.0.1 on 2026-02-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_alter_properties_options_alter_task_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="phone",
            field=models.CharField(default="", max_length=10),
        ),
    ]
