# Generated by Django 6.0.1 on 2026-02-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="properties",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
