# Generated by Django 6.0.1 on 2026-02-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_alter_properties_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="properties",
            name="booking_amount",
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=10),
        ),
        migrations.AlterField(
            model_name="properties",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
