# Generated by Django 6.0.1 on 2026-02-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_properties_booking_amount_alter_properties_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="paid",
            new_name="is_paid",
        ),
        migrations.AddField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                ],
                default="created",
                max_length=20,
            ),
        ),
    ]
